import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../style/globals.css'
import { Providers } from '../provider'

const pretendard = localFont({
  src: [
    {
      path: '../../../public/font/Pretendard-Regular.subset.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../../public/font/Pretendard-SemiBold.subset.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../../../public/font/Pretendard-Bold.subset.woff2',
      weight: '700',
      style: 'normal'
    }
  ],
  display: 'swap',
  variable: '--font-pretendard'
})

const elmsSans = localFont({
  src: '../../../public/font/ElmsSans-Bold.woff2',
  weight: '700',
  style: 'normal',
  display: 'swap',
  variable: '--font-elms'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="ko" className={`${pretendard.className} ${pretendard.variable} ${elmsSans.variable} h-full antialiased`}>
      <body className="flex h-full flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
