export { jdAPI } from './api/jd.api'
export { useRegisterJd } from './model/jd.mutations'
export { useJdInsight, useJdMeta, useJdDetail, useJdRecommendationTags, useJdRecommendations } from './model/jd.queries'
export { jdKeys, jdQueries } from './model/jd.keys'
export type { JdRegisterInput, JdCandidate, JdRecommendation, JdRecommendationTag } from './model/jd.types'
