import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './style/globals.css'
import { Providers } from './provider'
import { Toast } from '../shared/ui/toast'

const pretendard = localFont({
  src: [
    {
      path: '../../public/font/Pretendard-Regular.subset.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../public/font/Pretendard-SemiBold.subset.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../../public/font/Pretendard-Bold.subset.woff2',
      weight: '700',
      style: 'normal'
    }
  ],
  display: 'swap',
  variable: '--font-pretendard'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="ko" className={`${pretendard.className} ${pretendard.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <Toast />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
